### ISSUE TITLE
Please push the hiro-0.2 tag with the version currently on PyPI

### ISSUE THREAD

**Issue by olasd** [alisaifee/hiro#1]
Hi,

I'm considering packaging hiro for Debian. Unfortunately, the PyPI archive does not contain tests. I intend to do the packaging from git.

However, this git tree does not contain the 0.2 version as published on PyPI. Would you be willing to fix this? AFAICT it's just a matter of bumping __version__ and making a tag!

Thanks!

**Comment by alisaifee** [comment]
Hi @olasd, sorry about that - must have been an oversight when pushing the last release. I have pushed the tag now.
