### ISSUE TITLE
test suite is failing on arch arm64, armel, armhf and s390 within the Debian CI

### ISSUE THREAD

**Issue by tijuca** [alisaifee/hiro#9]
Hello,

I updated `hiro` within Debian unstable in order toe get the current most recent version ready for the Debian 12 (bookworm) release. I also added the upstream tests to the so called autopkgtest which will called after the package upload and the build of the source.

https://tracker.debian.org/news/1406403/accepted-hiro-051-2-source-into-unstable/
https://tracker.debian.org/pkg/hiro

Currently the internal tests are failing in the CI testing on the architectures [arm64](https://ci.debian.net/data/autopkgtest/testing/arm64/h/hiro/30134989/log.gz), [armel](https://ci.debian.net/data/autopkgtest/testing/armel/h/hiro/30135405/log.gz), [armhf](https://ci.debian.net/data/autopkgtest/testing/armhf/h/hiro/30135821/log.gz) and [s390x](https://ci.debian.net/data/autopkgtest/testing/s390x/h/hiro/30138041/log.gz).

The errors are a bit different, some failures happen on all platforms, and is not happen on `arm64`

```
                                                                                                         arm64   armel   armhf   s390x
test_freeze_target (tests.test_context_mgr.TestTimelineContext.test_freeze_target)                         x       x       x       x
test_decorated (tests.test_context_mgr.TestTimelineContext.test_decorated)                                         x       x       x
test_freeze_forward_unfreeze (tests.test_context_mgr.TestTimelineContext.test_freeze_forward_unfreeze)     x       x       x       x
```
Any idea what's going wrong here?

**Comment by alisaifee** [comment]
Hi! Thanks for the report.

The codebase/project is pretty outdated so I'm going to do a round of cleanup before digging into this bug (this will mean eventually doing a release which removes support for python < 3.7).

I did notice an issue with the use of an api that has been removed (`inspect.getargspec`) which I've fixed on master - though from the test runs you've shared that doesn't seem to be related.

To help move things along, is there a way for me to be able to reproduce one of those builds (I don't have access to any of those architectures)

**Comment by alisaifee** [comment]
I’m pretty sure the changes contained in this release will not fix the builds but I’ve released 1.0.0 which is compliant with Python 3.7-3.11 if you want to bump the version in the Debian package so that we’re working off the same baseline

**Comment by tijuca** [comment]
Thanks for your quick response, really appreciated!
I'll update the Debian packaging to your new version so we will see if something has changed.

**Comment by alisaifee** [comment]
> Thanks for your quick response, really appreciated!

No worries!

Some minor updates: I did actually see tests failing with `0.5.1` locally:
```
FAILED tests/test_context_mgr.py::TestTimelineContext::test_decorated - AttributeError: module 'inspect' has no attribute 'getargspec'
FAILED tests/test_context_mgr.py::TestTimelineContext::test_decorated_with_argument - AttributeError: module 'inspect' has no attribute 'getargspec'
FAILED tests/test_context_mgr.py::TestTimelineContext::test_freeze_forward_unfreeze - AssertionError: 57600 != 0 within 7 places (57600 difference)
FAILED tests/test_context_mgr.py::TestTimelineContext::test_freeze_target - hiro.errors.TimeOutofBounds: you've frozen time at a point before the epoch (-28800).hiro only supports going back to 1970/01/01 07:30:00
```

and these do not fail anymore with `1.x`

**Comment by tijuca** [comment]
This looks good now! So far the testing issues within the Debian CI are not visible any more, let's close that report now.

Thanks!
